### ISSUE TITLE
sdlog going crazy

### ISSUE THREAD

**Issue by parksw3** [parksw3/dynamicaltruncation#12]
See `data/posteriors`. `sdlog` values are way too high (on the order of 10^100). Trying to figure out what's wrong but can't...

**Comment by parksw3** [comment]
See `test/test.R` It looks like using the same name `sdlog := exp(log_sdlog)` is really bad. It gets iterated multiple times for whatever reason.

**Comment by parksw3** [comment]
I think I fixed it but keeping it on for you to check... and simplified targets.Rmd file for now to run everything again and test (haven't pushed this version, but I guess this is where I should've used a branch...).

**Comment by parksw3** [comment]
Tested and works now. Can be closed.

**Comment by seabbs** [comment]
This is very odd. Nice job fixing.
