### ISSUE TITLE
Debugging fitting methods based on exponential simulation results

### ISSUE THREAD

**Issue by parksw3** [parksw3/dynamicaltruncation#13]
![figure](https://user-images.githubusercontent.com/18031050/198850085-e98ab24e-3689-4b65-8e21-17eed018f120.png)

**Comment by parksw3** [comment]
* Truncation adjusted performs poorly when the delay is short probably because we're not taking censoring into account?
* Why is filtered performing poorly? It seems like we're filtering more than enough (or not)?
* Latent variable is having a hard time even in the stable case

**Comment by parksw3** [comment]
Found one problem. Previously, we had `delay_daily=floor(delay)` but this is different from what we actually observe, `stime_daily-ptime_daily`.

For example, if ptime=1.9 and stime=2, then true delay is 0.1 but the daily delay is 1. Instead, `floor(delay) = 0`. This might allow some of the discrete methods to work better.

**Comment by parksw3** [comment]
`stime_daily-ptime_daily` is breaking something now... need to fix...

**Comment by parksw3** [comment]
Changing `delay=stime_daily-ptime_daily` and `DT(, censored_obs_time := obs_at - (ptime_daily + 0.5))` fixed something because we're getting good estimates during the decay phase, when there should be barely any truncation. But it looks like other methods aren't working (all giving same estimates?). Two conclusiosn:

* Before, the latent variable was giving a different estimate only because all the discrete methods were using the wrong delay.
* Something is wrong. All methods are giving same answers (I think this issue may have been persistent before, but we just didn't see it? or maybe this is something new?).

**Comment by parksw3** [comment]
Fixed it. `DT(stime <= obs_time)` was problematic for the same reason as above. Changing to `DT(stime <= obs_at)` fixed it.

**Comment by parksw3** [comment]
![figure](https://user-images.githubusercontent.com/18031050/198862067-3368c60d-9568-485f-9e3a-5e9b16dfc31e.png)

New results. Truncation seems to be working for the fast growth phase but `r=0` scenario still looks buggy.

**Comment by parksw3** [comment]
![figure](https://user-images.githubusercontent.com/18031050/198863558-1f63c5f6-fb6d-47af-86f3-226fea7aef91.png)

New results with new parameters. 
* truncation_adjusted is really weird for the stable scenario 
* When I try to fit truncation_adjusted manually, it seems OK. Maybe something wrong with targets or somewhere in the pipeline...?

**Comment by parksw3** [comment]
![figure](https://user-images.githubusercontent.com/18031050/198864063-7872cdbf-dfa2-4494-9edd-b02485984d48.png)

Ran a new simulation with larger sample size. Also changing the labels on the xaxis and putting parameter names as a title.

* Everything looks a little more believable
* Truncation adjusted is overestimating sdlog by a large amount in the stable case...why?
* I've started using a longer delay so filtered needs to filter a lot more. But still better than naive.
* Compare sdlog estimates for naive vs censoring for the stable scenario. Censoring helps get better sdlog estimates. This might explain why naive truncation giving bad estimates for sdlog.

**Comment by seabbs** [comment]
Nice work. This is all looking good. 

> Compare sdlog estimates for naive vs censoring for the stable scenario. Censoring helps get better sdlog estimates. This might explain why naive truncation giving bad estimates for sdlog.

I think this is plausible though on the face of it I would have also expected a bias in the meanlog. 

The latent model looks like it slightly underestimates the sdlog - plausibly the issue with a uniform prior showing up?

**Comment by parksw3** [comment]
> The latent model looks like it slightly underestimates the sdlog - plausibly the issue with a uniform prior showing up?

I was wondering about this as well. I think the problem is that we can't tell from this one particular simulation. Is this just a bad sample (95% should contain truth 95% of the time so are we just in the 1/20 case)? Or is the method actually doing something wrong?

Either
* Increase sample size further. This is easy but just takes a longer time. I've been using smaller sample sizes for debugging purposes so far but we can bump it up easily when we feel ready.
* Run a bunch of simulations and test each method for a bunch of samples. Ideal but also way too time consuming...

**Comment by seabbs** [comment]
I've run the full pipeline on more samples etc here: https://github.com/parksw3/dynamicaltruncation/pull/20

Has some issues with the filtering models as can end up with no samples and therefore errors.

**Comment by seabbs** [comment]
As I said elsewhere we might want to do some more formal simulation-based calibration to get a handle on this but ideally if we can use what we are doing anyway that seems like a good idea as adds quite a lot of overhead.

**Comment by parksw3** [comment]
Going to close this for now. Don't think we need to look at these again.
