### ISSUE TITLE
How to specify outbreak scenarios

### ISSUE THREAD

**Issue by seabbs** [parksw3/dynamicaltruncation#15]
Now we have a stochastic outbreak model I am not sure this approach to defining when to estimate really makes sense. A simple change would be to just change to names (i.e as we don't know how time lines up to the outbreak). We could also set these based on the simulated outbreak in some way or do something else? 

https://github.com/parksw3/dynamicaltruncation/blob/a7e6744e6e5caf6226b0887a698fc5ba319e3906/_targets.Rmd#L254

**Comment by parksw3** [comment]
> We could also set these based on the simulated outbreak in some way

I think I already set the outbreak simulations so that the timing of the outbreak matches up with those names. Maybe not ideal but I think it's OK to pretend that we know how time lines up to the outbreak for simulations?

**Comment by seabbs** [comment]
Ah did you? Okay nice that is good enough for sure.
