### ISSUE TITLE
Comparing brms latent approach vs custom stan code; priors?

### ISSUE THREAD

**Issue by parksw3** [parksw3/dynamicaltruncation#18]
See `scripts/test_brms.R`

True:
```
logmean <- 1.8
logsd <- 0.5 ## note that log(0.5) = -0.69
```

brms:

```
                Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept           1.88      0.07     1.76     2.03 1.00     3444     2061
sigma_Intercept    -0.69      0.08    -0.84    -0.54 1.00     2849     2705
```

my code:

```
               mean     se_mean         sd       2.5%        25%        50%        75%      97.5%    n_eff      Rhat
mu        1.8554520 0.001252739 0.07509078  1.7284168  1.8034340  1.8488209  1.8985183  2.0191496 3592.956 0.9999661
logsigma -0.5910371 0.001381012 0.08031073 -0.7392728 -0.6469631 -0.5933721 -0.5409641 -0.4209328 3381.832 0.9994358
```

Pretty different estimates for log(sdlog). Maybe priors?

**Comment by parksw3** [comment]
But I'm still getting the weird negative correlation between ptime and stime estimates.
 
![Rplot03](https://user-images.githubusercontent.com/18031050/199166800-e943a017-b509-4d36-a190-7507a4ca79f8.png)

So...
* the correlation between ptime and stime is not a special feature or a bug of the brms code. I can replicate it with my custom model
* but priors on sdlog seem to matter...

**Comment by seabbs** [comment]
So the `brms` model has weakly informed student t priors

```
lprior += student_t_lpdf(Intercept | 3, 1, 2.5);
lprior += student_t_lpdf(Intercept_sigma | 3, 0, 2.5);
```

Whilst your custom code has a uniform priors on the Reals (right?) 

It isn't totally unsurprising the prior plays a role given the sample size and the general difficulty in fitting this model?

**Comment by parksw3** [comment]
Yes, I know that brms has weakly informative priors. I think this was more so my sanity check to see if the correlation had something to do with the brms code for whatever reason or if it was something I could replicate. 

I think prior seems more like a discussion point for now. Or for version 2 as you pointed out. In terms of discussion, we can think more along the lines of using vague priors vs something actually more informative (e.g., a new SARS-CoV-2 variant emerges, then should the prior reflect previous variants when the data are sparse?)

**Comment by parksw3** [comment]
Will do one more simulation with proper priors after https://github.com/parksw3/dynamicaltruncation/issues/26 is fixed. Then close this.

**Comment by parksw3** [comment]
So now they both give the same results, except that my code runs much faster (here, N=400). Going to try to spend some time trying to make the brms version faster.

```
> myfit$time()
$total
[1] 14.55718

$chains
  chain_id warmup sampling  total
1        1  9.356    5.088 14.444
2        2  9.217    5.086 14.303
3        3  8.874    5.087 13.961
4        4  9.136    5.076 14.212

> rstan::get_elapsed_time(latent_truncation_censoring_fit$fit) 
        warmup sample
chain:1 21.646  7.733
chain:2 20.827  7.823
chain:3 21.551  7.603
chain:4 20.774  7.702
```

**Comment by seabbs** [comment]
So I'd expect some difference as the `brms` version is carrying around a lot spare model infrastructure that yours doesn't have. Regardless of performance, we should definitely reparameterise to arbitrary window sizes as in your code. Playing around with your code I see an even larger difference in performance.

**Comment by seabbs** [comment]
Ah okay. So I think this is likely driven by vectorisation of the likelihood. Yours is vectorised and the `brms` code is not. There should be a way to implement the `bmrs` code as vectorised (there is a `loop` arg that can be changed) and then the model would need some reparameterisation.

**Comment by parksw3** [comment]
I thought loops were supposed to be just as fast as vectorization in c++? Maybe not?

I was wondering if defining ptime inside the function was slowing things down... tried to write a version that does most of calculations in `transformed parameters` but had to step away for a bit...

**Comment by seabbs** [comment]
> I thought loops were supposed to be just as fast as vectorization in c++? Maybe not?

Not when doing auto-diff on the likelihood - usually 10* performance difference or so

Yeah the `ptime` calc could also be an issue.

Just testing a loop version of your model to see what that does to relative performance.

**Comment by seabbs** [comment]
i.e playing with this: 

```
data {
  int<lower=1> N; //number of data
  real end_t;
  vector[N] ptime_lwr; //lower bound for primary event time
  vector[N] ptime_upr; //upper bound for primary event time
  vector[N] stime_lwr; //lower bound for secondary event time
  vector[N] stime_upr; //upper bound for secondary event time
}

parameters {
  real mu;
  real logsigma;
  vector<lower=0, upper=1>[N] ptime_uniform;
  vector<lower=0, upper=1>[N] stime_uniform;
}

transformed parameters {
  vector[N] ptime;
  vector[N] stime;
  vector[N] delay;
  vector[N] obs_time;
  real<lower=0> sigma;
  
  ptime = ptime_uniform .* (ptime_upr-ptime_lwr) + ptime_lwr;
  stime = stime_uniform .* (stime_upr-stime_lwr) + stime_lwr;
  delay = stime-ptime;
  obs_time = end_t - ptime;
  sigma = exp(logsigma);
}

model {
  //priors
  ptime_uniform ~ uniform(0, 1);
  stime_uniform ~ uniform(0, 1);
  
  target += student_t_lpdf(mu | 3, 1, 2.5);
  target += student_t_lpdf(logsigma | 3, 0, 2.5);
  for (i in 1:N) {
    target += lognormal_lpdf(delay[i] |mu, sigma) - lognormal_lcdf(obs_time[i] | mu, sigma);
  }

}

generated quantities {
  real lognormal_mean;
  
  lognormal_mean = exp(mu + sigma^2/2);
}
```

**Comment by seabbs** [comment]
> Not when doing auto-diff on the likelihood - usually 10* performance difference or so

Okay seeing a two times reduction in run time so not enough on its own to explain the performance difference.

**Comment by seabbs** [comment]
Just pushed a vectorised version that gives a small speed up. 

Agree that reparameterising this to be in terms of delay vs s and p time makes sense as a speed up target. 

```
    vector[n] p = y + pwindow;
    vector[n] s = to_vector(stime) + swindow;
    vector[n] d = s - p;
    vector[n] obs_time = to_vector(obs_t) - p;
```

**Comment by seabbs** [comment]
So looking at the stan code the bits that stand out are inefficient (and not needed truncation of the uniform (which it needs to stop `brms` complaining I think)), the matrix multiplication used for the design matrices that in this simple case don't do anything and are just wasted compute, and perhaps (though this seems unlikely) the initial conditions.

**Comment by parksw3** [comment]
> Agree that reparameterising this to be in terms of delay vs s and p time makes sense as a speed up target.

I'm not sure how this is going to make things faster. I was thinking that doing the latent model computation in `functions` instead of `transformed parameters` would be making things slow (no idea why but just a gut feeling).

I agree that all the matrix  multiplications are complete waste of time though. I will also poke around some more to see if I can make it faster.

I also already spotted a bug so will fix that soon too... still trying to wrap my head around backward vs forward...

**Comment by seabbs** [comment]
> I'm not sure how this is going to make things faster. I was thinking that doing the latent model computation in functions instead of transformed parameters would be making things slow (no idea why but just a gut feeling).

I don't think that should make a difference. The speed up here is that you need to do fewer additions so its only a tiny difference (which matches up with what I am seeing). 

The other thing to note is that the difference in speed scales non-linearly with sample size

**Comment by parksw3** [comment]
Got down much faster. 

```
> myfit$time()
$total
[1] 14.59064

$chains
  chain_id warmup sampling  total
1        1  8.848    5.088 13.936
2        2  9.369    5.078 14.447
3        3  8.862    5.102 13.964
4        4  8.698    5.101 13.799

> rstan::get_elapsed_time(latent_truncation_censoring_fit$fit)
        warmup sample
chain:1 10.765  6.089
chain:2 11.368  5.788
chain:3 10.791  5.828
chain:4 10.187  5.821
```

**Comment by parksw3** [comment]
Reparameterized to allow arbitrary window sizes. A little slower but not bad at all. For N=400:

```
        warmup sample
chain:1 11.814  5.867
chain:2 11.513  5.886
chain:3 11.673  5.906
chain:4 11.075  5.880
```
N=800
For N=800
```
        warmup sample
chain:1 29.098 18.610
chain:2 28.921 18.974
chain:3 29.585 18.864
chain:4 28.018 11.813
```

**Comment by seabbs** [comment]
Really nice. I updated to use a single function again and passing in the pre-calculated delays where possible. Very marginal speed improvements. Looks like the big cost was the handling of the priors for the windows which I guess makes sense.

**Comment by parksw3** [comment]
Really nice. Using delays is definitely cleaner. I thought there was a bug so I reverted it but I was wrong.
