### ISSUE TITLE
Sample size and replicates

### ISSUE THREAD

**Issue by seabbs** [parksw3/dynamicaltruncation#22]
As you suggested I think the current maximum sample size we are investigating is perhaps a bit large given the runtime issues. If we instead drop down to explore `n = 10, 100, 200, 400` we have more head room for looking at replicates etc which seems like it will be more useful. As long we discuss the scaling properties of each model (i.e across our explored samples) it feels like we can still make the same point as we would with a larger sample.

**Comment by seabbs** [comment]
After we chatted I think the decision is to explore

`n = 10, 100, 200` for outbreak settings and `n = 200` for fixed growth rate settings. Will make this update to the pipeline.

**Comment by parksw3** [comment]
Sounds awesome. Thank you! Will do more work on this when I get home.

**Comment by seabbs** [comment]
Running this now so should be updated tomorrow.
