### ISSUE TITLE
important error in the latent truncation model

### ISSUE THREAD

**Issue by parksw3** [parksw3/dynamicaltruncation#26]
https://github.com/parksw3/dynamicaltruncation/blob/84167e74cd404a042db799624748d66c08b092eb/R/models.R#L95

I believe these have to be ptime_daily and stime_daily. Ran the readmefile with `fn=make_stancode` and am seeing that continuous time ptime is passed. Seems like a pretty important change (even though it's a tiny piece of code) so wanted to make an issue before making the change.

This means that we've been consistently overestimating the amount of truncation (because estimated ptime is always greater than the true ptime). I think this could've been one source of bias? maybe the correlations have to do something with this (or not)? Need to run some of the tests again after we fix this.

**Comment by seabbs** [comment]
Damn you are definitely correct. Good spot. My bad.
