### ISSUE TITLE
replace latent model with the new version

### ISSUE THREAD

**Issue by parksw3** [parksw3/dynamicaltruncation#29]
I wrote `latent_truncation_censoring_adjusted_delay_zero`, which allows zero delays for the latent model. It seems to be working (`test/zero.R`) and just as fast as the original model when we don't have zero delays (`test/zero_comparespeed.R`).

Think we should replace `latent_truncation_censoring_adjusted_delay` with the new one if we think both points above are true. But didn't want to do that before getting reviewed.

**Comment by parksw3** [comment]
I guess this is what the pull request is for...

**Comment by seabbs** [comment]
This is really nice!

I was a little concerned about settings where we might have overlapping primary and secondary observation windows and generally distressed by for loops so hacked around on this a bit (see `main`). I don't know if there is much between the implementations so happy to go with whichever. I think speed-wise your for loop-based approach is fractionally faster and maybe easier to follow?

**Comment by parksw3** [comment]
I like avoiding loops but I'm confused about this (I'm at school and don't have my stan-running laptop machine with me right now so can't test numerically but): 

```
pwindow = pwindow_raw .* (to_vector(vreal2) + swindow .* to_vector(vreal4));
```

`vreal4` is `woverlap` which is either 0 or 1. So if there's overlap, `woverlap = 1`, then `pwindow` gets larger? 

Consider a case where `ptime_upr = 1`, `ptime_lwr = 0`, `stime_upr=0`, `stime_lwr=0` such that there is an exact overlap. Then, 

```
as.numeric((stime_lwr - ptime_lwr + 1) <= (ptime_upr - ptime_lwr)) = 1
```

And so `pwindow` can be greater than 1? Did you mean to do something like: 

```
pwindow = pwindow_raw .* (to_vector(vreal2) .* (1-to_vector(vreal4))) + swindow .* to_vector(vreal4));
```

**Comment by parksw3** [comment]
I think there may be some examples where both of our approaches might fail. For example, what happens if 0 < p < 1 and 0 < s < 2. If a sample is at stime = 1.5 then ptime is going to be between 0 and 1.5. So maybe better to start the inference with `ptime` and then work out `stime`?

I do think that 
```
pwindow = pwindow_raw .* (to_vector(vreal2) .* (1-to_vector(vreal4))) + swindow .* to_vector(vreal4));
```
this might be a bit clunky and hard to read though. And don't see much disadvantage in using loops.

**Comment by seabbs** [comment]
haha if you thought that was clunky you should look at what I just pushed. Some really pointless optimisation happening here.

**Comment by seabbs** [comment]
> Consider a case where ptime_upr = 1, ptime_lwr = 0, stime_upr=0, stime_lwr=0 such that there is an exact overlap. Then,

So for this case I guess we need to check what `stime_upr` is.

**Comment by parksw3** [comment]
> Consider a case where ptime_upr = 1, ptime_lwr = 0, stime_upr=0, stime_lwr=0 such that there is an exact overlap. Then,

Sorry, typo. I meant stime_upr = 1. I was just trying to make a point that 

```
pwindow = pwindow_raw .* (to_vector(vreal2) + swindow .* to_vector(vreal4));
```

this doesn't seem right. 

```
haha if you thought that was clunky you should look at what I just pushed. 
```

Just looking at it now and trying to parse what's going on...

**Comment by seabbs** [comment]
>  If a sample is at stime = 1.5 then ptime is going to be between 0 and 1.5. So maybe better to start the inference with ptime and then work out time?

So this is what redefining the upper bound of `ptime` was meant to deal with.

**Comment by parksw3** [comment]
A few typos in the code. Making suggestions here.

> So this is what redefining the upper bound of `ptime` was meant to deal with.

I'm not sure that this is a good idea. Right now, we have

```
pwindow_upr := ifelse(
          (stime_lwr - ptime_upr) <= -1, 
          stime_lwr - ptime_lwr,
          ptime_upr - ptime_lwr
        )
```

Consider a case in which `ptime_lwr=0`, `ptime_upr=1`, `stime_lwr=0`, and `stime_upr=2`. Then, `pwindow_upr = stime_lwr - ptime_lwr = 0`. So here, I think you mean to write `stime_upr - ptime_lwr` instead of `stime_lwr - ptime_lwr`.

And here's the reason why redefining the upper bound is bad. In the same case, we have `pwindow_upr = stime_lwr - ptime_lwr = 2`. But there's no reason for us to sample between 1 and 2 for `ptime` since we know that it's between 0 and 1.

But actually, sampling `ptime` first doesn't help either because we can have `ptime_lwr=0`, `ptime_upr=2`, `stime_lwr=1`, and `stime_upr=2`. Same problem...

Also:

```
pwindow[woverlap] = (to_vector(vreal2[woverlap]) +  swindow[woverlap]) .*
      pwindow_raw[woverlap];
```

Think this can be simplified:

```
pwindow[woverlap] = (swindow[woverlap]) .*
      pwindow_raw[woverlap];
```

right? (sorry to keep suggesting without making changes myself. Can't test any of this on the current laptop so don't want to break the code without knowing.)

**Comment by seabbs** [comment]
> I think there may be some examples where both of our approaches might fail. For example, what happens if 0 < p < 1 and 0 < s < 2. If a sample is at stime = 1.5 then ptime is going to be between 0 and 1.5. So maybe better to start the inference with ptime and then work out time?

Yes agree. I have reformulated along these lines but as I currently have it currently there are some rather large sampling problems that may be on me or may indicate more general issues with the shape of the posterior. 

In terms of posterior shape I am not clear there is any information when we are assuming a uniform prior so perhaps we should be making a censoring correction for these values vs trying to model explicitly. 

I think as written though it clears up your other points. For some of the simplifications you suggested the reason to keep them (they are gone now but similar ones exist in this implementation) ifsfor the cases when we have very oddly sized censoring windows. That being said if we are going to keep this complexity we perhaps may need to explore it at least a little (though I am not sure that is a good idea).

**Comment by seabbs** [comment]
In conclusion - I have broken everything 😆

**Comment by seabbs** [comment]
Just went to run this and I am seeing the following when running targets. 

```
✖ error branch standata_truncation_adjusted_a7cd01ec
Error: Truncation bounds are invalid: lb >= ub

✔ skip branch standata_truncation_adjusted_b1647d3c
• start branch standata_truncation_adjusted_ef56afa9
• record workspace standata_truncation_adjusted_8f0e551d
✖ error branch standata_truncation_adjusted_8f0e551d
Error: Some responses are outside of the truncation bounds.
```

Got to drop off and do other things now but will have a look at this later if time and if not tomorroow.

**Comment by parksw3** [comment]
Hm, I don't see why we would get this error. It looks like the error must be coming from here:

```
trunc(lb = 1e-3, ub = censored_obs_time)
```

when `lb >= ub`. But we would only get this if `censored_obs_time = 0`. Currently, we have

```
censored_obs_time := obs_at - (ptime_lwr + (ptime_upr - ptime_lwr) / 2)
```

And so we can get `censored_obs_time <= 0` if the midpoint between `ptime_lwr` and `ptime_upr` is greater than `obs_at`. This should never happen if we're dealing with a one day width but can happen if we're dealing with more than one day width. So... do we actually have examples of that... let me see....

**Comment by parksw3** [comment]
Running 
```
min(sapply(list_observations, function(x) min(x$censored_obs_time)))
```
gives `0.5` so we should never get ub < lb... what's going on!!!!

**Comment by parksw3** [comment]
Ahhhh I found it! Something wrong with Ebola data. Looking at one of the workspaces, we see that `delay_daily > censored_obs_time` in some cases.

**Comment by seabbs** [comment]
I think (🤞🏻) these issues are now as resolved as they are getting.
